config/routes.rb
Rails.application.routes.draw do
  get 'homes/thanks'
  root to: 'posts#index'
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  
  devise_for :users, :controllers => {
        :sessions => 'users/sessions',
        :registrations => 'users/registrations',
        :omniauth_callbacks => 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
  end
  resources :posts
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable,
           :omniauthable, omniauth_providers: %i[facebook twitter google_oauth2]
    
    has_many :posts, dependent: :destroy
    has_many :post_images, dependent: :destroy
    
    # いいね機能
    has_many :likes, dependent: :destroy
    has_many :like_posts, through: :likes, source: :post
    
    def liked_by?(post_id)
      likes.where(post_id: post_id).exists?
    end
    
    attachment :profile_image
          
    has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
    has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
    has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
    has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人
    
    def follow(user_id)
      follower.create(followed_id: user_id)
    end
  
    def unfollow(user_id)
      follower.find_by(followed_id: user_id).destroy
    end
  
    def following?(user)
      following_user.include?(user)
    end
    
    # omniauthのコールバック時に呼ばれるメソッド
    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
    end
    
  end
  

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end
  
    # POST /resource/confirmation
    # def create
    #   super
    # end
  
    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end
  
    # protected
  
    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  
    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
  

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
    def google_oauth2
      callback_for(:google)
    end
  
    # common callback method
    def callback_for(provider)
      @user = User.from_omniauth(request.env["omniauth.auth"])
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
      else
        session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
    
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]
  
    # You should also create an action method in this controller like this:
    # def twitter
    # end
  
    # More info at:
    # https://github.com/heartcombo/devise#omniauth
  
    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end
  
    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end
  
    # protected
  
    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
    
  end
  

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end
  
    # POST /resource/password
    # def create
    #   super
    # end
  
    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end
  
    # PUT /resource/password
    # def update
    #   super
    # end
  
    # protected
  
    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end
  
    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
  

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]
  
    # GET /resource/sign_up
    # def new
    #   super
    # end
  
    # POST /resource
    # def create
    #   super
    # end
  
    # GET /resource/edit
    # def edit
    #   super
    # end
  
    # PUT /resource
    # def update
    #   super
    # end
  
    # DELETE /resource
    # def destroy
    #   super
    # end
  
    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end
  
    # protected
  
    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end
  
    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end
  
    # The path used after sign up.
    def after_sign_up_path_for(resource)
      homes_thanks_path
    end
  
    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
  

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]
  
    # GET /resource/sign_in
    def new
      @user = User.new
    end
  
    # POST /resource/sign_in
    # def create
    #   super
    # end
  
    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end
  
    # protected
  
    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
  

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end
  
    # POST /resource/unlock
    # def create
    #   super
    # end
  
    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end
  
    # protected
  
    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end
  
    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    before_action :authenticate_user!, except: [:index]
    
    def show
      @user = User.find(params[:id])
      @posts = @user.posts
      @following_users = current_user.following_user
      @follower_users = current_user.follower_user
    end
    
    def edit
      @user = User.find(params[:id])
      # format.js
    end
   
    def update
      @user = User.find(params[:id])
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
          format.js { @status = "success" }
          # format.js {}
          # binding.pry
        else
          render "edit"
          format.js {}
        end
      end
    end
    
    def mypage
      @following_users = current_user.following_user
      @follower_users = current_user.follower_user
    end
    
    
    private
    
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end
    
  end
  

app/views/users/_edit.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <h3>プロフィールを編集</h3>
    <%= form_with model: @user, method: :patch do |f| %>
      <div class="field">
      <%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "100x100" %>
      <%= f.attachment_field :profile_image, :placeholder => "プロフィール画像" %>
      </div>
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :自己紹介 %><br>
        <%= f.text_area :introduction, autofocus: true %>
      </div>
      <%= f.submit "保存", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/_profile.html.erb
<div class="user-introduction">
    <div class="projects-section-header ">
        <p>
          <%= attachment_image_tag @user, :profile_image, format: 'jpeg', size: "500x500", fallback: "no_image.jpg" %>
          <%= @user.name %>
        </p>
    </div>
    <p class="introduction">
    <%= @user.introduction %>
    </p>
</div>

app/views/users/edit.js.erb
$("#user-modal").html("<%= escape_javascript(render 'edit') %>");
$("#user-modal").modal("show");

app/views/users/show.html.erb
<% content_for :css do %>
    <%= stylesheet_link_tag 'nav' %>
    <%= stylesheet_link_tag 'main_layouts' %>
<% end %>
<%= render "common/sidebar" %>
  <div class="app-content">
    <div class="projects-section">
        <div class="projects-section-header">
            <p>My Page</p>
            <p class="time "><%= Date.today %></p>
        </div>
        <!--ユーザー編集のAjax-->
        <%= render partial: "users/profile", locals:{ user: @user } %>
        <div class="projects-section-line">
            <div class="projects-status">
                <div class="item-status">
                    <span class="status-number"><%= @user.posts.count %></span>
                    <span class="status-type">Total Posts</span>
                </div>
                <div class="item-status">
                    <span class="status-number"><%= @user.follower.count %></span>
                    <span class="status-type">Followings</span>
                </div>
                <div class="item-status">
                    <span class="status-number"><%= @user.followed.count %></span>
                    <span class="status-type">Follower</span>
                </div>
            </div>
            <div class="view-actions">
                <% if @user.id == current_user.id %>
                    <%= link_to "Edit Profile", edit_user_path(@user), remote: true, class: "btn btn-primary w-10" %>
                    <div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
                <% end %>
                <% if current_user != @user %>
                    <% if current_user.following?(@user) %>
                      <%= link_to 'Unfollow', user_relationships_path(@user.id), method: :delete, remote: true, class: "btn btn-primary" %>
                    <% else %>
                      <%= link_to 'Follow', user_relationships_path(@user.id), method: :POST, remote: true, class: "btn btn-primary" %>
                    <% end %>
                <% end %>
                <button class="view-btn list-view " title="List View ">
                  <svg xmlns="http://www.w3.org/2000/svg " width="24 " height="24 " viewBox="0 0 24 24 " fill="none " stroke="currentColor " stroke-width="2 " stroke-linecap="round " stroke-linejoin="round " class="feather feather-list ">
                    <line x1="8 " y1="6 " x2="21 " y2="6 " />
                    <line x1="8 " y1="12 " x2="21 " y2="12 " />
                    <line x1="8 " y1="18 " x2="21 " y2="18 " />
                    <line x1="3 " y1="6 " x2="3.01 " y2="6 " />
                    <line x1="3 " y1="12 " x2="3.01 " y2="12 " />
                    <line x1="3 " y1="18 " x2="3.01 " y2="18 " />
                　</svg>
                </button>
                <button class="view-btn grid-view active " title="Grid View">
                  <svg xmlns="http://www.w3.org/2000/svg " width="20 " height="20 " viewBox="0 0 24 24 " fill="none " stroke="currentColor " stroke-width="2 " stroke-linecap="round " stroke-linejoin="round " class="feather feather-grid ">
                    <rect x="3 " y="3 " width="7 " height="7 " />
                    <rect x="14 " y="3 " width="7 " height="7 " />
                    <rect x="14 " y="14 " width="7 " height="7 " />
                    <rect x="3 " y="14 " width="7 " height="7 " />
                　</svg>
                </button>
            </div>
        </div>
        <div class="project-boxes jsGridView">
        <% @posts.each do |post| %>
            <div class="project-box-wrapper post-action-<%= post.id %>">
                <div class="project-box">
                    <div class="project-box-header">
                        <div class="project-box-header-introduction">
                            <%= link_to attachment_image_tag(post.user, :profile_image, format: 'jpeg', size: "50x50", fallback: "no_image.jpg", size:'100x100'), user_path(post.user.id) %>
                            <%= link_to_if post.user, post.user.name, user_path(post.user.id) %>
                        </div>
                        <div class="post-action-#{ post.id }">
                          <%= link_to(content_tag(:i, nil, class: 'fas fa-edit'), edit_post_path(post), remote: true) %>
                          <%= link_to(content_tag(:i, nil, class: 'fas fa-trash-alt'), post_path(post), method: :delete, remote: true, data: { confirm: '本当に削除しますか？' }) %>
                        </div>
                    </div>
                    <div class="project-box-content-header">
                        <p class="box-content-header "><%=safe_join(post.body.split("\n"),tag(:br))%></p>
                    </div>
                    <div class="project-box-footer ">
                        <div class="participants ">
                            <div id="likes_buttons_<%= post.id %>">
                                <%= render partial: 'posts/post', locals: {post: post} %>
                            </div>
                        </div>
                        <div class="days-left " style="color: #ff942e; ">
                            <%= l post.created_at, format: :default %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
        </div>
    </div>
      <!--フォロー、フォロワー欄（幅をコンパクトにしたい）-->
    <div class="messages-section ">
        <div class="follow-bar-right">
            <div class="projects-section-header ">
                <p>Following</p>
            </div>
            <% @following_users.each do |following_user| %>
            <div class="messages ">
                <div class="message-box">
                    <%= link_to (user_path(following_user.id)) do %>
                    <p><%= attachment_image_tag(following_user, :profile_image, format: 'jpeg', size: "50x50", fallback: "no_image.jpg", size:'100x100') %></p>
                    <div class="message-content ">
                        <div class="message-header ">
                            <div class="name "><%= following_user.name %></div>
                        </div>
                    <% end %>
                        <p class="message-line ">
                            ##
                        </p>
                    </div>
                </div>
            </div>
        <% end %>
        </div>
        <div class="follow-bar-left">
            <div class="projects-section-header ">
                <p>Follower</p>
            </div>
            <% @follower_users.each do |follower_user| %>
                <div class="messages ">
                    <div class="message-box ">
                        <%= link_to (user_path(follower_user.id)) do %>
                        <p><%= attachment_image_tag(follower_user, :profile_image, format: 'jpeg', size: "30x30", fallback: "no_image.jpg", size:'100x100') %></p>
                        <div class="message-content ">
                            <div class="message-header ">
                                <div class="name"><%= follower_user.name %></div>
                            </div>
                        <% end %>
                            <p class="message-line">
                                #
                            </p>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
  </div>
<!--<script type="text/javascript" src="main_layouts.js"></script>-->

app/views/users/update.js.erb
$(".user-introduction").html("<%= j(render("profile")) %>");
$("#user-modal").modal("hide");