config/routes.rb
Rails.application.routes.draw do
  get 'homes/thanks'
  root to: 'posts#index'
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  
  devise_for :users, :controllers => {
        :sessions => 'users/sessions',
        :registrations => 'users/registrations',
        :omniauth_callbacks => 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
  end
  resources :posts
end

app/models/post.rb
class Post < ApplicationRecord
  
    belongs_to :user
    has_many :post_images
    
    has_many :likes, dependent: :destroy
    has_many :users, through: :likes
    
    attachment :image
    validates :body, presence: true, length: { maximum: 140 }
    
  end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
    before_action :authenticate_user!
  
    def index
      @users = User.all
      @post = Post.new
      @posts = Post.order(created_at: :desc)
      @following_users = current_user.following_user
      @follower_users = current_user.follower_user
    end
    
    def create
      @post = Post.new(post_params)
      @post.user_id = current_user.id
      # Post.create(post_params)
      respond_to do |format|
        if @post.save
          @posts = Post.order(created_at: :desc)
          format.html { redirect_to @posts, notice: 'User was successfully created.' }
          format.json { render :index, status: :ok, location: @post }
          format.js
        else
          render :index
        end
      end
    end
    
    def show
      @post = Post.find(params[:id])
      @user = @post.user
    end
    
    def edit
      @post = Post.find(params[:id])
    end
    
    def update
      @post = Post.find(params[:id])
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
          format.js { @status = "success" }
          # format.js {}
          # binding.pry
        else
          render "edit"
          format.js {}
        end
      end
    end
    
    def destroy
      @post = Post.find(params[:id])
      @post_id = @post.id
      @post.destroy
      respond_to do |format|
        format.js
      end
      
    end
    
    private
    
    def post_params
      params.require(:post).permit(:body, :image, :user_id)
    end
  end
  

app/views/posts/_edit.html.erb
<!-- Button trigger modal -->
<!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">-->
<!--  Launch demo modal-->
<!--</button>-->

<!-- Modal -->
<!--<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">-->
<!--  <div class="modal-dialog" role="document">-->
<!--    <div class="modal-content">-->
<!--      <div class="modal-header">-->
<!--        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>-->
<!--        <button type="button" class="close" data-dismiss="modal" aria-label="Close">-->
<!--          <span aria-hidden="true">&times;</span>-->
<!--        </button>-->
<!--      </div>-->
<!--      <div class="modal-body">-->
<!--        ...-->
<!--      </div>-->
<!--      <div class="modal-footer">-->
<!--        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>-->
<!--        <button type="button" class="btn btn-primary">Save changes</button>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->

<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/posts/_index.html.erb
<div class="project-boxes jsGridView">
    <% @posts.each do |post| %>
    <!--ここから下がqiitaでは部分テンプレート化されている-->
        <div class="project-box-wrapper post-action-<%= post.id %>">
            <div class="project-box">
                <div class="project-box-header">
                    <div class="project-box-header-introduction">
                        <%= link_to attachment_image_tag(post.user, :profile_image, format: 'jpeg', size: "50x50", fallback: "no_image.jpg", size:'100x100'), user_path(post.user.id) %>
                        <%= link_to_if post.user, post.user.name, user_path(post.user.id) %>
                    </div>
                    <!--Editはlink_toではなく、spanタグにしてjsファイルに処理を書く-->
                    <div class="post-action-#{ post.id }">
                        <%= link_to(content_tag(:i, nil, class: 'fas fa-edit'), edit_post_path(post), remote: true) %>
                        <!--<div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>-->
                        <%= link_to(content_tag(:i, nil, class: 'fas fa-trash-alt'), post_path(post), method: :delete, remote: true, data: { confirm: '本当に削除しますか？' }) %>
                    </div>
                </div>
                <div class="project-box-content-header">
                    <p class="box-content-header "><%=safe_join(post.body.split("\n"),tag(:br))%></p>
                </div>
                <div class="project-box-footer ">
                    <div id="likes_buttons_<%= post.id %>">
                        <%= render partial: 'posts/post', locals: {post: post} %>
                    </div>
                    <div class="days-left">
                        <%= l post.created_at, format: :default %>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/posts/_newpost.html.erb
<div class="container">
    <div class="row">
        <button type="button" class="btn btn-primary w-10" data-toggle="modal" data-target="#exampleModal">
          New Post
        </button>
        
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">新規投稿</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <%= form_for @post, remote: true do |f| %>
                  <div class="modal-body">
                    <%= render 'layouts/error_messages', model: @post %>
                    <div class="post">
                      <%= f.text_area :body, size: "40x5", :placeholder => 'いまどんな気持ち？' %>
                      <div class="image_wrapper">
                        <div class="item_image_btn">
                          <%= f.attachment_field :image, id: "file" %>
                        </div>
                        <div id="img_field" onClick="$('#file').click()" >
                          <p class="image-select">画像選択</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <%= f.submit "投稿する", class: "btn btn-primary" %>
                  </div>
              <% end %>
            </div>
          </div>
        </div>
    </div>
</div>

app/views/posts/_post.html.erb
<% if current_user.liked_by?(post.id) %>
  <!--<p> -->
    <%= link_to destroy_like_path(post), class: "like-link", method: :DELETE, remote: true do %>
      <i class="fa fa-heart unlike-btn"></i>
    <%= post.likes.count %>
  <!--</p>-->
  <% end %>
<% else %>
  <p>
    <%= link_to create_like_path(post), class: "like-link", method: :POST, remote: true do %>
      <i class="fa fa-heart like-btn"></i>
    <% end %>
    <%= post.likes.count %>
  </p>
<% end %>

app/views/posts/create.js.erb
<!--$(".project-boxes jsGridView").html("<%#= j(render("index"), :locals => { posts: @posts}) %>");-->
<!--$(".project-boxes jsGridView").html("<%#= j(render partial: 'index', :locals => { posts: @posts}) %>");-->
<!--$(".project-boxes jsGridView").html("<%#= j(render 'index', :locals => { posts: @posts}) %>");-->

<!--$("js-form").val('');-->

$("textarea").val("");
$("#exampleModal").modal("hide");
$(".newposts").html("<%= escape_javascript(render 'index', posts: @posts) %>");

app/views/posts/destroy.js.erb
$(".post-action-<%= @post.id %>").remove();
<!--alert('huhuhu');-->

app/views/posts/edit.js.erb
$(".fas fa-edit").html("<%= escape_javascript(render 'edit') %>");
$(".fas fa-edit").modal("show");

app/views/posts/index.html.erb
<% content_for :css do %>
    <%= stylesheet_link_tag 'nav' %>
    <%= stylesheet_link_tag 'main_layouts' %>
<% end %>
<%= render "common/sidebar" %>
        <div class="app-content ">
            <div class="projects-section ">
                <div class="projects-section-header ">
                    <p>Tweets</p>
                    <p class="time "><%= Date.today %></p>
                </div>
                <div class="projects-section-line">
                    <div class="projects-status ">
                        <div class="item-status ">
                            <span class="status-number "><%= @posts.count %></span>
                            <span class="status-type ">Total Posts</span>
                        </div>
                        <div class="item-status ">
                            <span class="status-number "><%= @users.count %></span>
                            <span class="status-type ">Upcoming</span>
                        </div>
                    </div>
                    <div class="view-actions">
                            <button type="button" class="btn btn-primary w-10" data-toggle="modal" data-target="#exampleModal">
                              New Post
                            </button>
                            
                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                              <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">新規投稿</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                      <span aria-hidden="true">&times;</span>
                                    </button>
                                  </div>
                                  <%= form_for @post, remote: true do |f| %>
                                      <div class="modal-body">
                                        <%= render 'layouts/error_messages', model: @post %>
                                        <div class="post">
                                          <%= f.text_area :body, size: "40x5", :placeholder => 'いまどんな気持ち？' %>
                                          <div class="image_wrapper">
                                            <div class="item_image_btn">
                                              <%= f.attachment_field :image, id: "file" %>
                                            </div>
                                            <div id="img_field" onClick="$('#file').click()" >
                                              <p class="image-select">画像選択</p>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <%= f.submit "投稿する", class: "btn btn-primary" %>
                                      </div>
                                  <% end %>
                                </div>
                              </div>
                            </div>
                        <button class="view-btn list-view " title="List View ">
                          <svg xmlns="http://www.w3.org/2000/svg " width="24 " height="24 " viewBox="0 0 24 24 " fill="none " stroke="currentColor " stroke-width="2 " stroke-linecap="round " stroke-linejoin="round " class="feather feather-list ">
                            <line x1="8 " y1="6 " x2="21 " y2="6 " />
                            <line x1="8 " y1="12 " x2="21 " y2="12 " />
                            <line x1="8 " y1="18 " x2="21 " y2="18 " />
                            <line x1="3 " y1="6 " x2="3.01 " y2="6 " />
                            <line x1="3 " y1="12 " x2="3.01 " y2="12 " />
                            <line x1="3 " y1="18 " x2="3.01 " y2="18 " />
                        　</svg>
                        </button>
                        <button class="view-btn grid-view active " title="Grid View ">
                          <svg xmlns="http://www.w3.org/2000/svg " width="20 " height="20 " viewBox="0 0 24 24 " fill="none " stroke="currentColor " stroke-width="2 " stroke-linecap="round " stroke-linejoin="round " class="feather feather-grid ">
                            <rect x="3 " y="3 " width="7 " height="7 " />
                            <rect x="14 " y="3 " width="7 " height="7 " />
                            <rect x="14 " y="14 " width="7 " height="7 " />
                            <rect x="3 " y="14 " width="7 " height="7 " />
                        　</svg>
                        </button>
                    </div>
                </div>
                <div class="newposts">
                    <%= render partial: 'posts/index', locals: { posts: @posts } %>
                </div>
                
            </div>
            <!--フォロー、フォロワー欄（幅をコンパクトにしたい）-->
            <div class="messages-section ">
                <div class="follow-bar-right">
                    <div class="projects-section-header ">
                        <p>Following</p>
                    </div>
                    <% @following_users.each do |following_user| %>
                    <div class="messages ">
                        <div class="message-box">
                            <%= link_to (user_path(following_user.id)) do %>
                            <p><%= attachment_image_tag(following_user, :profile_image, format: 'jpeg', size: "50x50", fallback: "no_image.jpg", size:'100x100') %></p>
                            <div class="message-content ">
                                <div class="message-header ">
                                    <div class="name "><%= following_user.name %></div>
                                </div>
                            <% end %>
                                <p class="message-line ">
                                    ##
                                </p>
                            </div>
                        </div>
                    </div>
                <% end %>
                </div>
                <div class="follow-bar-left">
                    <div class="projects-section-header ">
                        <p>Follower</p>
                    </div>
                    <% @follower_users.each do |follower_user| %>
                        <div class="messages ">
                            <div class="message-box ">
                                <%= link_to (user_path(follower_user.id)) do %>
                                <p><%= attachment_image_tag(follower_user, :profile_image, format: 'jpeg', size: "30x30", fallback: "no_image.jpg", size:'100x100') %></p>
                                <div class="message-content ">
                                    <div class="message-header ">
                                        <div class="name "><%= follower_user.name %></div>
                                    </div>
                                <% end %>
                                    <p class="message-line">
                                        #
                                    </p>
                                </div>
                            </div>
                        </div>
                    <% end %>
            </div>
        </div>
    </div>
    <!--<script type="text/javascript" src="/tuitta-/app/assets/javascripts/main_layouts.js"></script>-->

app/views/posts/show.html.erb
<% content_for :css do %>
    <%= stylesheet_link_tag 'nav' %>
    <%= stylesheet_link_tag 'main_layouts' %>
<% end %>
<%= render "common/sidebar" %>

        <div class="app-content ">
            <div class="projects-section ">
                <div class="projects-section-header ">
                    <p>Tweet</p>
                    <p class="time "><%= Date.today %></p>
                </div>
                <div class="projects-section-line ">
                    <div class="projects-status ">
                        <div class="item-status ">
                            <span class="status-number ">45</span>
                            <span class="status-type ">In Progress</span>
                        </div>
                        <div class="item-status ">
                            <span class="status-number ">24</span>
                            <span class="status-type ">Upcoming</span>
                        </div>
                        <div class="item-status ">
                            <span class="status-number ">62</span>
                            <span class="status-type ">Total Projects</span>
                        </div>
                    </div>
                    <div class="view-actions ">
                        <button class="view-btn list-view " title="List View ">
                          <svg xmlns="http://www.w3.org/2000/svg " width="24 " height="24 " viewBox="0 0 24 24 " fill="none " stroke="currentColor " stroke-width="2 " stroke-linecap="round " stroke-linejoin="round " class="feather feather-list ">
                            <line x1="8 " y1="6 " x2="21 " y2="6 " />
                            <line x1="8 " y1="12 " x2="21 " y2="12 " />
                            <line x1="8 " y1="18 " x2="21 " y2="18 " />
                            <line x1="3 " y1="6 " x2="3.01 " y2="6 " />
                            <line x1="3 " y1="12 " x2="3.01 " y2="12 " />
                            <line x1="3 " y1="18 " x2="3.01 " y2="18 " />
                        　</svg>
                        </button>
                        <button class="view-btn grid-view active " title="Grid View ">
                          <svg xmlns="http://www.w3.org/2000/svg " width="20 " height="20 " viewBox="0 0 24 24 " fill="none " stroke="currentColor " stroke-width="2 " stroke-linecap="round " stroke-linejoin="round " class="feather feather-grid ">
                            <rect x="3 " y="3 " width="7 " height="7 " />
                            <rect x="14 " y="3 " width="7 " height="7 " />
                            <rect x="14 " y="14 " width="7 " height="7 " />
                            <rect x="3 " y="14 " width="7 " height="7 " />
                        　</svg>
                        </button>
                    </div>
                </div>
                <div class="project-boxes jsGridView ">
                    <div class="project-box-wrapper ">
                        <div class="project-box " style="background-color: #fee4cb; ">
                            <div class="project-box-header ">
                                <div class="more-wrapper ">
                                    <button class="project-btn-more ">
                                        <svg xmlns="http://www.w3.org/2000/svg " width="24 " height="24 " viewBox="0 0 24 24 " fill="none " stroke="currentColor " stroke-width="2 " stroke-linecap="round " stroke-linejoin="round " class="feather feather-more-vertical ">
                                          <circle cx="12 " cy="12 " r="1 " />
                                          <circle cx="12 " cy="5 " r="1 " />
                                          <circle cx="12 " cy="19 " r="1 " />
                                      　</svg>
                                  　</button>
                                </div>
                            </div>
                            <div class="project-box-content-header">
                                <p class="box-content-header "><%=safe_join(@post.body.split("\n"),tag(:br))%></p>
                            </div>
                            <div class="box-progress-wrapper ">
                                <p class="box-progress-header ">Progress</p>
                                <div class="box-progress-bar ">
                                    <span class="box-progress " style="width: 60%; background-color: #ff942e "></span>
                                </div>
                                <p class="box-progress-percentage ">60%</p>
                            </div>
                            <div class="project-box-footer ">
                                <div class="participants ">
                                    #
                                </div>
                                <div class="days-left " style="color: #ff942e; ">
                                    <%= l @post.created_at, format: :default %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
<!--<script type="text/javascript" src="main_layouts.js"></script>-->